Repository IBM/ibm-mongodb-operator, pull requests merged in 2020-06, with the labels that each got.

#103 add time stamp
  common/scripts/promote-to-beta.sh
Labels: approved, lgtm, size/XS

#104 fully quilified DNS name
  pkg/controller/mongodb/certificate.go
  pkg/controller/mongodb/initconfigmap.go
Labels: approved, lgtm, size/S

#105 no cluster domain
  pkg/controller/mongodb/certificate.go
  pkg/controller/mongodb/initconfigmap.go
Labels: approved, lgtm, size/XS

#106 Revert dns
  pkg/controller/mongodb/certificate.go
  pkg/controller/mongodb/initconfigmap.go
Labels: approved, lgtm, size/S

#107 move 1.1.1 to stable
  deploy/olm-catalog/ibm-mongodb-operator/ibm-mongodb-operator.package.yaml
Labels: approved, lgtm, size/XS

#108 Fix for certification
  deploy/olm-catalog/ibm-mongodb-operator/1.1.2/ibm-mongodb-operator.v1.1.2.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/mongodb/initconfigmap.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/S

#111 add yaml for scc
  README.md
Labels: approved, lgtm, size/M

#112 update digest
  deploy/operator.yaml
Labels: lgtm, size/XS

#113 promote 1.1.3 to stable
  deploy/olm-catalog/ibm-mongodb-operator/ibm-mongodb-operator.package.yaml
Labels: approved, lgtm, size/XS
