Repository IBM/ibm-mongodb-operator, pull requests merged in 2020-08, with the labels that each got.

#114 CICD changes
  Makefile
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/S

#116 Remove monkey
  .gitignore
  deploy/role.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#117 Dynamic scale
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/crds/operator.ibm.com_mongodbs_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.1.4/ibm-mongodb-operator.v1.1.4.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/mongodb_types.go
  pkg/controller/mongodb/mongoconfigmap.go
  pkg/controller/mongodb/mongodb_controller.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/L

#118 1.1.4 alm fix
  deploy/olm-catalog/ibm-mongodb-operator/1.1.4/ibm-mongodb-operator.v1.1.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.1.4/operator.ibm.com_mongodbs_crd.yaml
Labels: approved, lgtm, size/M

#119 fix Cpu to CPU
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/S

#120 redirect to bootstrap logs stderr
  pkg/controller/mongodb/initconfigmap.go
Labels: approved, lgtm, size/XS

#121 forgot prefix for sha
  deploy/olm-catalog/ibm-mongodb-operator/1.1.4/ibm-mongodb-operator.v1.1.4.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#122 add probes
  deploy/olm-catalog/ibm-mongodb-operator/1.1.4/ibm-mongodb-operator.v1.1.4.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#123 rebuilt two images
  deploy/olm-catalog/ibm-mongodb-operator/1.1.4/ibm-mongodb-operator.v1.1.4.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#124 remove product version
  deploy/olm-catalog/ibm-mongodb-operator/1.1.4/ibm-mongodb-operator.v1.1.4.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/XS

#125 Change affinity
  deploy/operator.yaml
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/M

#126 1.1.4 default values
  pkg/controller/mongodb/mongodb_controller.go
Labels: approved, lgtm, size/M

#127 Patch 1
  README.md
  deploy/olm-catalog/ibm-mongodb-operator/1.1.4/ibm-mongodb-operator.v1.1.4.clusterserviceversion.yaml
Labels: lgtm, size/M

#128 csv bump and csv labels
  Makefile
  common/scripts/promote-to-beta.sh
  deploy/olm-catalog/ibm-mongodb-operator/1.1.5/ibm-mongodb-operator.v1.1.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.1.5/operator.ibm.com_mongodbs_crd.yaml
  deploy/olm-catalog/ibm-mongodb-operator/ibm-mongodb-operator.package.yaml
  version/version.go
Labels: approved, lgtm, size/L
