Repository IBM/ibm-mongodb-operator, pull requests merged in 2020-05, with the labels that each got.

#90 Only support update sts
  pkg/controller/mongodb/mongodb_controller.go
Labels: approved, lgtm, size/M

#91 Support digest
  deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.1.0/ibm-mongodb-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/mongodb/mongodb_controller.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/M

#92 Product ver3.4.0
  deploy/olm-catalog/ibm-mongodb-operator/1.1.0/ibm-mongodb-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/XS

#93 update csv to use digests
  deploy/olm-catalog/ibm-mongodb-operator/1.1.0/ibm-mongodb-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#94 make limit and request same
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/S

#95 digest for release 1.1.0
  deploy/olm-catalog/ibm-mongodb-operator/1.1.0/ibm-mongodb-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#96 add beta channel
  deploy/olm-catalog/ibm-mongodb-operator/1.1.0/ibm-mongodb-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/ibm-mongodb-operator.package.yaml
Labels: approved, lgtm, size/S

#97 initial 1.1.1 dev
  Makefile
  deploy/olm-catalog/ibm-mongodb-operator/1.1.1/ibm-mongodb-operator.v1.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.1.1/operator.ibm.com_mongodbs_crd.yaml
  deploy/olm-catalog/ibm-mongodb-operator/ibm-mongodb-operator.package.yaml
  version/version.go
Labels: approved, lgtm, size/L

#100 Content cert changes
  deploy/crds/operator.ibm.com_mongodbs_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.1.1/ibm-mongodb-operator.v1.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.1.1/operator.ibm.com_mongodbs_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/mongodb/certificate.go
  pkg/controller/mongodb/service_account.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/L

#101 update description and doc
  README.md
  deploy/olm-catalog/ibm-mongodb-operator/1.1.1/ibm-mongodb-operator.v1.1.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S
