Repository IBM/ibm-mongodb-operator, pull requests merged in 2020-02, with the labels that each got.

#1 init project
  .gitignore
  CONTRIBUTING.md
  Makefile
  OWNERS
  SECURITY_CONTACTS
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/.githooks/pre-commit
  common/scripts/codecov.sh
  common/scripts/config_docker.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_mongodbs_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/operator/group.go
  pkg/apis/operator/v1alpha1/doc.go
  pkg/apis/operator/v1alpha1/mongodb_types.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_mongodb.go
  pkg/controller/controller.go
  pkg/controller/mongodb/icp-service.go
  pkg/controller/mongodb/mongodb_controller.go
  pkg/controller/mongodb/service.go
  pkg/controller/mongodb/statefulset.go
  tools.go
  version/version.go
Labels: approved, lgtm, size/XXL

#3 Update role and rolebind
  Makefile
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/M

#4 Add storage class for mongodb
  Makefile
  deploy/crds/operator.ibm.com_mongodbs_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/mongodb_types.go
  pkg/controller/mongodb/mongodb_controller.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/M

#6 create cluster ca certification
  pkg/certification/create_certification.go
  pkg/controller/mongodb/mongodb_controller.go
Labels: approved, size/M

#7 Add scc
  pkg/controller/mongodb/mongodb_controller.go
  pkg/controller/mongodb/mongodb_scc.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/L

#8 add admin secret and metric secret
  deploy/crds/operator.ibm.com_mongodbs_crd.yaml
  pkg/apis/operator/v1alpha1/mongodb_types.go
  pkg/controller/mongodb/mongodb_controller.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/M

#11 Update role rules
  Makefile
  deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml
  deploy/role.yaml
Labels: approved, size/S

#10 fix the certificate issue of mongo
  common/config/.golangci.yml
  pkg/certification/create_certification.go
  pkg/controller/mongodb/certificate.go
  pkg/controller/mongodb/initconfigmap.go
  pkg/controller/mongodb/mongodb_controller.go
Labels: approved, lgtm, size/L

#14 Add CSV file
  Makefile
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/operator.ibm.com_mongodbs_crd.yaml
  deploy/olm-catalog/ibm-mongodb-operator/ibm-mongodb-operator.package.yaml
Labels: approved, lgtm, size/L

#17 Add storageclass check
  deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
  pkg/controller/mongodb/mongodb_controller.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/M

#19 make mnogodb work well on OCP 4.x
  deploy/role.yaml
  pkg/controller/mongodb/installconfigmap.go
  pkg/controller/mongodb/mongodb_controller.go
  pkg/controller/mongodb/mongodb_scc.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/L

#22 save storage class in status
  Makefile
  deploy/crds/operator.ibm.com_mongodbs_crd.yaml
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/operator.ibm.com_mongodbs_crd.yaml
  pkg/apis/operator/v1alpha1/mongodb_types.go
  pkg/controller/mongodb/mongodb_controller.go
Labels: approved, lgtm, size/M

#18 Update csv
  .gitignore
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/ibm-mongodb-operator.package.yaml
Labels: approved, lgtm, size/S

#24 add mongodb client cert
  pkg/controller/mongodb/certificate.go
  pkg/controller/mongodb/mongodb_controller.go
Labels: approved, lgtm, size/S

#30 Expose image in CR
  deploy/crds/operator.ibm.com_mongodbs_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/operator.ibm.com_mongodbs_crd.yaml
  pkg/apis/operator/v1alpha1/mongodb_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/mongodb/mongodb_controller.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/L

#32 add controller for PVC
  common/config/.golangci.yml
  deploy/crds/operator.ibm.com_mongodbs_crd.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/mongodb_types.go
  pkg/controller/mongodb/mongodb_controller.go
Labels: approved, lgtm, size/M

#34 remove hard coded namespace
  go.sum
  pkg/controller/mongodb/certificate.go
  pkg/controller/mongodb/icp-service.go
  pkg/controller/mongodb/initconfigmap.go
  pkg/controller/mongodb/installconfigmap.go
  pkg/controller/mongodb/mongoconfigmap.go
  pkg/controller/mongodb/mongodb_controller.go
  pkg/controller/mongodb/service.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/S

#36 Udpate mongodb role and rolebinding
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/operator.ibm.com_mongodbs_crd.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/M

#37 Update cluster-ca-cert to mongodb-root-ca-cert
  pkg/controller/mongodb/certificate.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/XS

#38 add finalizer for rbac
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/XS

#40 add rbac for mongodb status
  Makefile
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#41 Use reader to list storageclass
  pkg/controller/mongodb/mongodb_controller.go
Labels: approved, lgtm, size/XS

#39 Add cert-manager as the required crd
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#43 Wiredtiger limit
  pkg/controller/mongodb/mongoconfigmap.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/XS

#47 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS
