Repository IBM/ibm-mongodb-operator, pull requests merged in 2020-03, with the labels that each got.

#54 run update to make sure we are at latest packages
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#56 tags updated to 3.4.0 for q1
  deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#58 statefulset is v1
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#61 add annotations for release
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/XS

#63 create random string for admin password
  pkg/controller/mongodb/mongodb_controller.go
Labels: approved, lgtm, size/S

#28 integrate with cert-manager
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/mongodb/certificate.go
  pkg/controller/mongodb/mongodb_controller.go
Labels: approved, lgtm, size/L

#68 Random username
  deploy/crds/operator.ibm.com_mongodbs_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml
  deploy/olm-catalog/csv-config.yaml
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/0.0.1/operator.ibm.com_mongodbs_crd.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/mongodb_types.go
  pkg/controller/mongodb/mongodb_controller.go
Labels: approved, lgtm, size/M

#70 Operator annotation
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#71 Bump Mongodb version to 1.0.0
  Makefile
  deploy/olm-catalog/ibm-mongodb-operator/1.0.0/ibm-mongodb-operator.v1.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.0.0/operator.ibm.com_mongodbs_crd.yaml
  deploy/olm-catalog/ibm-mongodb-operator/ibm-mongodb-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/S

#72 Add a build for 1.0.0 version
  Makefile
Labels: approved, size/XS

#73 Remove plaintext secret option
  deploy/crds/operator.ibm.com_mongodbs_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.0.0/ibm-mongodb-operator.v1.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.0.0/operator.ibm.com_mongodbs_crd.yaml
  pkg/apis/operator/v1alpha1/mongodb_types.go
  pkg/controller/mongodb/mongodb_controller.go
Labels: approved, lgtm, size/M

#74 Redhat cert changes
  .osdk-scorecard.yaml
  Makefile
  common/Makefile.common.mk
  deploy/crds/operator.ibm.com_mongodbs_crd.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.0.0/ibm-mongodb-operator.v1.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.0.0/operator.ibm.com_mongodbs_crd.yaml
Labels: approved, lgtm, size/L

#75 Add display name
  deploy/olm-catalog/ibm-mongodb-operator/1.0.0/ibm-mongodb-operator.v1.0.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#76 Csv annotations
  common/scripts/delete-csv.sh
  deploy/crds/operator.ibm.com_mongodbs_crd.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.0.0/ibm-mongodb-operator.v1.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-mongodb-operator/1.0.0/operator.ibm.com_mongodbs_crd.yaml
Labels: approved, lgtm, size/M

#78 Fix runasuser
  pkg/controller/mongodb/installconfigmap.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, lgtm, size/XS

#79 make mongodb use its own service account
  deploy/olm-catalog/ibm-mongodb-operator/1.0.0/ibm-mongodb-operator.v1.0.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/mongodb/mongodb_controller.go
  pkg/controller/mongodb/service_account.go
  pkg/controller/mongodb/statefulset.go
Labels: approved, size/M

#80 remove release version image tag and push
  Makefile
Labels: approved, size/XS
