Repository IBM/ibm-mongodb-operator, pull requests merged in 2021-04, with the labels that each got.

#200 operand bump
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, size/S

#201 remove note
  README.md
Labels: approved, size/XS

#202 update go
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: approved, size/XS

#204 update tags
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, size/XS

#205 Pvc configurable
  Makefile
  api/v1alpha1/mongodb_types.go
  config/samples/mongodb_v1alpha1_mongodb.yaml
  controllers/mongodb_controller.go
  controllers/statefulset.go
Labels: approved, lgtm, size/M

#199 liveness and readiness probes
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, size/M
