Repository IBM/ibm-mongodb-operator, pull requests merged in 2021-08, with the labels that each got.

#222 min Kube Version
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
Labels: approved, size/XS

#223 golang 1.15.13
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: approved, size/XS

#225 rh mirroring
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
Labels: approved, size/XS

#226 remove deprecated apis
  config/crd/bases/operator.ibm.com_mongodbs.yaml
  config/crd/patches/cainjection_in_mongodbs.yaml
  config/crd/patches/webhook_in_mongodbs.yaml
  config/default/webhookcainjection_patch.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
Labels: approved, size/S

#228 fix pre install
  bundle/manifests/operator.ibm.com_mongodbs.yaml
  config/crd/bases/operator.ibm.com_mongodbs.yaml
Labels: approved, size/L

#229 update mongodb CRD
  bundle/manifests/operator.ibm.com_mongodbs.yaml
  config/crd/bases/operator.ibm.com_mongodbs.yaml
Labels: approved, size/L

#231 bump version
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: lgtm, approved, size/S

#232 opt-in to CICD automation
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  base_images.json
  common/scripts/config_docker.sh
Labels: size/S

#234 version bump to match CICD
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: approved, size/S
