Repository IBM/ibm-mongodb-operator, pull requests merged in 2022-05, with the labels that each got.

#283 related images schema
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/XS

#280 Update fix aqua issues
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#285 version increment for 3.19
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S
