Repository IBM/ibm-mongodb-operator, pull requests merged in 2023-01, with the labels that each got.

#310 [Cloud Pak 3.0] bump up mongo csv to v4.0
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#311 Added changes to support multiple namespaces
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-mongodb-operator.clusterserviceversion.yaml
  main.go
Labels: size/M

#313 version bump for CS 3.19.8
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#314 go version updated to 1.18.10
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS

#315 artifactory change
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/scripts/config_docker.sh
Labels: size/S

#316 artifactory change
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/scripts/config_docker.sh
Labels: size/S

#317 version bump for 3.24
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S
