Repository IBM/ibm-mongodb-operator, pull requests merged in 2023-05, with the labels that each got.

#342 cicd version bump automation for pipelines/CS-ltsr.json
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/M

#344 fix matchLabels in topologySpreadConstraints
  controllers/statefulset.go
Labels: size/XS

#345 update pullpolicy to IfNotPresent
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
Labels: size/XS

#346 port multizone support to CP 3.0
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  controllers/statefulset.go
Labels: size/S

#347 correct the metrics container readiness probe
  controllers/statefulset.go
Labels: size/S

#348 remove mongo operandrequst created by 3.x CS
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/genericresources.go
  controllers/mongodb_controller.go
Labels: size/M

#349 cp3 img updates
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: size/S

#350 go version updated to 1.20.4
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS
