Repository IBM/ibm-mongodb-operator, pull requests merged in 2023-03, with the labels that each got.

#330 cicd version bump automation for pipelines/CS-ltsr.json
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/M

#332 update go version to 1.19.7
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS

#333 fix twistlock issues
  go.mod
  go.sum
Labels: size/L

#334 Report CR status
  Makefile
  api/v1alpha1/mongodb_types.go
  bundle/manifests/operator.ibm.com_mongodbs.yaml
  controllers/mongodb_controller.go
  controllers/resourcestatus.go
Labels: size/L

#335 update crd to allow additional fields in status subresource
  bundle/manifests/operator.ibm.com_mongodbs.yaml
Labels: size/XS
