Repository IBM/ibm-mongodb-operator, pull requests merged in 2023-08, with the labels that each got.

#359 cicd version bump automation for pipelines/CS-cd.json
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#360 cicd version bump automation for pipelines/CS-ltsr.json
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/M

#361 go version updated to 1.20.7
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS

#362 go version updated to 1.20.7
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS

#363 update CRD description for certification
  bundle/manifests/operator.ibm.com_mongodbs.yaml
  config/crd/bases/operator.ibm.com_mongodbs.yaml
Labels: size/XS
