Repository IBM/ibm-mongodb-operator, pull requests merged in 2023-02, with the labels that each got.

#312 Mongodb multiple namespace support
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-mongodb-operator.clusterserviceversion.yaml
  main.go
Labels: size/M

#319 correct key namespace-scope ENV
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-mongodb-operator.clusterserviceversion.yaml
Labels: size/XS

#318 migrate v1alpha1 certs to v1
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/certmanager/certificate.yaml
  config/manifests/bases/ibm-mongodb-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/certificate.go
  controllers/mongodb_controller.go
  go.mod
  go.sum
  main.go
Labels: size/XXL

#320 Update README.md
  README.md
Labels: lgtm, size/XS

#322 fix lint error
  controllers/mongodb_controller.go
  main.go
Labels: lgtm, size/XS

#323 fix issuer creation
  controllers/mongodb_controller.go
Labels: lgtm, size/XS

#325 merge release-ltsr to master
  base_images.json
  controllers/mongodb_controller.go
  main.go
Labels: size/L

#326 remove ibm-cert-manager operandrequest from csv for Bedrock4.0
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/M

#328 keep version 4.0.0 for bedrock 4.0
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S
