Repository IBM/ibm-mongodb-operator, pull requests merged in 2023-04, with the labels that each got.

#338 cicd version bump automation for pipelines/CS-ltsr.json
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/M

#339 update go version to 1.19.7
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS

#337 podAntiAffinity to support multiple availability zones
  controllers/statefulset.go
Labels: size/XS

#340 remove metrics container
  api/v1alpha1/mongodb_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_mongodbs.yaml
  common/scripts/add-image-shas.sh
  config/crd/bases/operator.ibm.com_mongodbs.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-mongodb-operator.clusterserviceversion.yaml
  controllers/initconfigmap.go
  controllers/mongodb_controller.go
  controllers/statefulset.go
Labels: size/L
