Repository IBM/ibm-mongodb-operator, pull requests merged in 2023-06, with the labels that each got.

#351 cicd version bump automation for pipelines/CS-ltsr.json
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/M

#352 go version updated to 1.19.10
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS

#353 cicd version bump automation for pipelines/CS-cd.json
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: lgtm, size/S

#354 1.19.10-bullseye flavour
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS
