Repository IBM/ibm-mongodb-operator, pull requests merged in 2023-09, with the labels that each got.

#365 gopkg.in/yaml.v3 v3.0.1
  go.mod
  go.sum
Labels: size/XS

#366 update CRD description for certification
  bundle/manifests/operator.ibm.com_mongodbs.yaml
  config/crd/bases/operator.ibm.com_mongodbs.yaml
Labels: size/XS

#367 cicd version bump automation for pipelines/CS-ltsr.json
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/M

#369 go version updated to 1.20.8
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  go.mod
  go.sum
Labels: size/S

#370 Update release cd for 4.3.0
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S
