Repository IBM/ibm-mongodb-operator, pull requests merged in 2023-07, with the labels that each got.

#355 sec fixes
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  go.mod
  go.sum
Labels: size/S

#356 golang.org/x/net updated to v0.12.0
  go.mod
  go.sum
Labels: size/S

#357 cicd version bump automation for pipelines/CS-ltsr.json
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: lgtm, approved, size/M

#358 go version updated to 1.19.11
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS
