Repository IBM/ibm-mongodb-operator, pull requests merged in 2023-10, with the labels that each got.

#371 cicd version bump automation for pipelines/CS-ltsr.json
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/M

#372 ephemeral storage inclusion
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/samples/mongodb_v1alpha1_mongodb.yaml
  controllers/mongodb_controller.go
  controllers/statefulset.go
Labels: size/M

#373 add lebels to CR
  api/v1alpha1/mongodb_types.go
  bundle/manifests/operator.ibm.com_mongodbs.yaml
  controllers/mongodb_controller.go
Labels: size/S

#374 fix multi-arch issue
  controllers/statefulset.go
Labels: size/S

#375 added missing comma in CR section of csv
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
Labels: size/XS

#376 security fixes for 3.19.17
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  go.mod
  go.sum
Labels: size/M

#377 sec fixes
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  go.mod
  go.sum
Labels: size/M

#378 go version updated to 1.20.9
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS
