Repository IBM/ibm-mongodb-operator, pull requests merged in 2023-11, with the labels that each got.

#379 cicd version bump automation for pipelines/CS-ltsr.json
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/M

#381 go version updated to 1.20.11
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS

#382 Update release cd 21 nov 2023 10 07
  bundle/manifests/ibm-mongodb-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S
